name = "LoopManagers"
uuid = "d33d4f76-8fbe-47a6-acd9-ead534c583ff"
authors = ["The ClimFlows contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.8"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
