name = "LoopManagers"
uuid = "d33d4f76-8fbe-47a6-acd9-ead534c583ff"
authors = ["The ClimFlows contributors"]
version = "0.1.2"

[deps]
HostCPUFeatures = "3e5b6fbb-0976-4d2c-9146-d79de83f2fb0"
ManagedLoops = "36a4119d-6b73-4371-88fe-ba2d91f5495d"
Polyester = "f517fe37-dbe3-4b94-8317-1923a5111588"
SIMD = "fdea26ae-647d-5447-a871-4b548cad5224"

[weakdeps]
KernelAbstractions = "63c18a36-062a-441e-b654-da1e3ab1ce7c"

[extensions]
KA_Ext = "KernelAbstractions"

[compat]
HostCPUFeatures = "0.1"
KernelAbstractions = "0.9"
ManagedLoops = "0.1.3"
Polyester = "0.7"
SIMD = "3.4"
julia = "1.8"

[extras]
KernelAbstractions = "63c18a36-062a-441e-b654-da1e3ab1ce7c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
